import streamlit as st
import math

st.set_page_config(page_title="Buah dan Vitamin Didalam-nya", layout="centered")

# Sidebar for input
with st.sidebar:
    st.header("Menu")
    selection = st.radio("Ingin Tahu Tentang Apa?", ["Kenali Vitamin", "Fungsi dan Sumber Vitamin", "Kekurangan dan Kelebihan", "Fakta Menarik", "Tentang Kami"])

# Konten berdasarkan pilihan
if selection == "Kenali Vitamin":
    st.title("Yuk Kenali Macam-macam Vitamin!")
    st.markdown("---")
    st.subheader("Vitamin Itu Apa?")
    st.markdown("---")
    st.write("kita sudah tidak asing dengan vitamin, tetapi masih banyak orang yang jarang mengkonsumsi vitamin. Sebenarnya vitamin itu apa sih?")
    st.write("Vitamin adalah senyawa organik mikronutrien penting yang dibutuhkan tubuh dalam jumlah kecil untuk menjalankan berbagai fungsi biokimiawi. Vitamin tidak dapat disintesis oleh tubuh sendiri dan umumnya harus diperoleh dari makanan.") 
    st.subheader("Apa Saja Macam Vitamin?")
    st.markdown("---")
    st.write("Vitamin dibagi menjadi dua kelompok utama yakni vitamin larut lemak (A, D, E, K) dan vitamin larut air (C dan B kompleks).")
elif selection == "Fungsi dan Sumber Vitamin":
    st.title("Sebenarnya, Apa Saja Fungsi dan Sumber Dari Vitamin?")
    st.markdown("---")
    st.write("Vitamin Memiliki Berbagai Fungsi Dari Berbagai Sumber loh! namun vitamin memiliki fungsi umum sebagai kofaktor dalam reaksi kimia yang dikatalisis oleh enzim, membantu tubuh dalam pertumbuhan, perkembangan, dan fungsi normal.")
    st.markdown("---")
    st.header("Vitamin A")
    st.markdown("---")
    st.subheader("Fungsi Vitamin A")
    st.write("- Menjaga kesehatan mata (penglihatan malam)")
    st.write("- Mendukung sistem imun")
    st.write("- Membantu pertumbuhan dan perkembangan sel")
    st.subheader("Sumber Vitamin A")
    st.write("Hati💖, telur🥚, susu🍼, wortel🥕, ubi🍠, bayam🥬, mangga🥭")
    st.markdown("---")
    st.header("Vitamin B")
    st.markdown("---")
    st.subheader("Fungsi Vitamin B1 (Thiamin)")
    st.write("- Mengubah karbohidrat menjadi energi")
    st.write("- Mendukung fungsi saraf dan otot")
    st.subheader("Sumber Alami Vitamin B1 (Thiamin)")
    st.write("Beras merah 🍚, daging babi 🍖, biji bunga matahari 🌻")  
    st.subheader("Fungsi Vitamin B2 (Riboflavin)")
    st.write("- Membantu produksi energi")
    st.write("- Menjaga kesehatan kulit dan mata")
    st.subheader("Sumber Alami Vitamin B2 (Riboflavin)")
    st.write("Susu 🥛, telur 🥚, hati 🐄, sayur hijau 🥬")
    st.subheader("Fungsi Vitamin B3 (Niasin)")
    st.write("- Metabolisme energi")
    st.write("- Menjaga kulit dan pencernaan")
    st.write("- Membantu menurunkan kolesterol")
    st.subheader("Sumber Alami Vitamin B3 (Niasin)")
    st.write("Daging ayam 🍗, ikan tuna 🐟, gandum utuh 🌾")
    st.subheader("Fungsi Vitamin B5 (Pantotenat)")
    st.write("- Sintesis hormon dan metabolisme lemak")
    st.write("- Pembentukan sel darah merah")
    st.subheader("Sumber Alami Vitamin B5 (Pantotenat)")
    st.write("Alpukat 🥑, jamur 🍄, ayam 🍗, biji-bijian 🌰")
    st.subheader("Fungsi Vitamin B6 (Piridoksin)")
    st.write("- Metabolisme protein dan memproduksi neurotransmiter")
    st.write("- mendukung fungsi otak dan suasana hati")
    st.subheader("Sumber Alami Vitamin B6 (Piridoksin)")
    st.write("Pisang 🍌, kentang 🥔, ayam 🍗, ikan 🐟")
    st.subheader("Fungsi Vitamin B7 (Biotin)")
    st.write("- Mendukung kesehatan rambut, kulit, dan kuku")
    st.write("- membantu metabolisme lemak dan protein")
    st.subheader("Sumber Alami Vitamin B7 (Biotin)")
    st.write("Telur 🥚, kacang-kacangan 🥜, hati 🐄, kembang kol 🥦")
    st.subheader("Fungsi Vitamin B9 (Asam Folat)")
    st.write("- Membantu pembentukan sel darah merah")
    st.write("- Mencegah cacat lahir pada janin")
    st.write("- Sintesis DNA dan RNA")
    st.subheader("Sumber Alami Vitamin B9 (Asam Folat)")
    st.write("Sayur hijau 🥬, jeruk 🍊, kacang 🫘, roti fortifikasi 🍞")
    st.subheader("Fungsi Vitamin B12 (Kobalamin)")
    st.write("- Membantu pembentukan sel darah merah")
    st.write("- Menjaga fungsi sistem saraf")
    st.write("- Mendukung metabolisme energi")
    st.subheader("Sumber Alami Vitamin B12 (Kobalamin)")
    st.write("Daging 🥩, ikan 🐟, telur 🥚, susu 🥛")
elif selection == "Kekurangan dan Kelebihan":
    st.write("Ini konten untuk Mengetahui Kekurangan.")
elif selection == "Fakta Menarik":
    st.write("Ini konten untuk Mengetahui Fakta Menarik Vitamin.")

st.markdown("---")
st.caption("📘 Made with Streamlit for educational purposes.")
